### ISSUE TITLE
PHP7

### ISSUE THREAD

**Issue by TheFox** [TheFox/tumblr-parser#1]
Ready for PHP7? Testing.

**Comment by p-realinho** [comment]
Hey!
First of all, thank you for the repo! I haven't really used it yet but, I've been looking for something like this for quite some time, and even started to build something similar, so I know it'll be useful in the near future.
I just wanted to make a quick suggestion or two...
You might wanna add to the readme that the parser needs PHP 7.0 ... I eventually figured it out after a couple minutes, but the first time I tried to fire it up I ran into a bunch of errors and immediately though the whole thing was broken lol.
Also, the easiest way to give the examples a quick spin would probably be to copy the folder to the project's root (I tried to run it from `vendor\thefox\tumblr-parser\example` and it couldn't find the autoloader and whatnot).

I'm gonna go actually try it now :) Thank you again.

**Comment by TheFox** [comment]
Hello!

Thank you for your input. I can, of course, add the requirements to the README file.

The best way to install this library is via [Composer](https://getcomposer.org/). This resolves all dependencies. It also checks your required PHP version.

Best regards,
Christian

**Comment by p-realinho** [comment]
Oh, okay...
(I think) the problem is I'm using XAMPP, so although I used Composer, the PHP version it'll use will still be the one that comes with XAMPP.

Thanks anyways :)
